#variables:
before_script:
  - docker info

stages:
  - docker-build


build-docker-alpine:
  stage: docker-build
  script:
    - cd alpine
    - docker build --network=host -t catdeployed/postal:alpine .

build-docker-ubuntu:
  stage: docker-build
  script:
    - cd ubuntu
    - docker build --network=host -t catdeployed/postal:ubuntu .
