#variables:
before_script:
  - docker info

stages:
  - docker-build
  - cleanup


build-docker-alpine:
  stage: docker-build
  script:
    - cd alpine
    - docker build --network=host -t catdeployed/postal:alpine .

build-docker-ubuntu:
  stage: docker-build
  script:
    - cd ubuntu
    - docker build --network=host -t catdeployed/postal:ubuntu .

test-docker-ubuntu:
  stage: tests
  script:
    - /opt/postal/bin/postal make-user

docker-cleanup:
  stage: cleanup
  script:
    - docker system prune -af
