version: 2
jobs:
  build-alpine:
    machine: true
    working_directory: ~/repo/alpine
    steps:
      - checkout:
          path: ~/repo
      - run: 
          name: Build Postal Docker Container
          command: cd alpine && docker build -t catdeployed/postal:latest -t catdeployed/postal:alpine .
      - run:
          name: Skip this job for Pull Requests
          command: '[[ -v CIRCLE_PR_NUMBER ]] && circleci step halt || true'
      - run:
          name: Login to Docker Hub
          command: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run:
          name: Push to Docker Hub
          command: docker push catdeployed/postal:latest
workflows:
  version: 2
  nightly:
    triggers:
      - schedule:
          cron: "0 * * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - build-alpine
  commit:
    jobs:
      - build-alpine
