version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run: 
          name: Build Postal Docker Container
          command: docker build -t catdeployed/postal:dev .
      - run:
          name: Skip this job for Pull Requests
          command: '[[ -v CIRCLE_PR_NUMBER ]] && circleci step halt || true'
      - run:
          name: Login to Docker Hub
          command: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run:
          name: Push to Docker Hub
          command: docker push catdeployed/postal:dev

workflows:
  version: 2
  nightly:
    triggers:
      - schedule:
          cron: "0 * * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - build
  commit:
    jobs:
      - build
          context: Docker Hub
