version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run: 
        name: Build Postal Docker Container
        command: docker build -t postal:latest .
      #- run:
      #  name: Skip this job for Pull Requests
      #  command: '[[ -v CIRCLE_PR_NUMBER ]] && circleci step halt || true'
workflows:
  version: 2
  nightly:
    triggers:
      - schedule:
          cron: "0 * * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - build
  commit:
    jobs:
      - build
